#!/usr/bin/env bash

# TODO proper regexp with capturing group
#PATTERN_FORMAT="#\[\([^]]*\)\]"
PATTERN_FORMAT="#\[\([^]]*\)\]"

# TODO use tput

if [[ $1 == '--debug' ]]; then
  echo "$*" | awk -f ./tmux-printer.awk
else
  eval "echo -e $(echo "$*" | awk -f ./tmux-printer.awk)"
fi
