#!/usr/bin/env bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ $1 == '--debug' ]]; then
  echo "$*" | awk -f $CURRENT_DIR/tmux-printer.awk
else
  eval "echo -e \"$(echo "$*" | awk -f $CURRENT_DIR/tmux-printer.awk)\""
fi
